Clean up Dockerfile.

diff --git a/web/Dockerfile b/web/Dockerfile
--- a/web/Dockerfile
+++ b/web/Dockerfile
@@ -5,13 +5,11 @@ FROM node:16-alpine AS deps
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
-# Install dependencies based on the preferred package manager
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+# Install npm dependencies
+COPY package.json package-lock.json* ./
 RUN \
-    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-    else echo "Lockfile not found." && exit 1; \
+    if [ -f package-lock.json ]; then npm ci; \
+    else echo "package-lock.json not found." && exit 1; \
     fi
 
 
@@ -26,9 +24,7 @@ COPY . .
 # Uncomment the following line in case you want to disable telemetry during the build.
 # ENV NEXT_TELEMETRY_DISABLED 1
 
-#RUN yarn build
-
-# If using npm comment out above and use below instead
+# Build the production app for deployment
 RUN npm run build
 
 # Production image, copy all the files and run next
